### ISSUE TITLE
newCredential.response?.getAuthenticatorData is not a function

### ISSUE THREAD

**Issue by ForNeVeR** [dodobrands/WebAuthn.Net#1]
I'm trying to use KeePassXC's passkey support with WebAuthn.Net, and it fails.

My environment is Windows 11.

1. Install [the latest snapshot version KeePassXC](https://snapshot.keepassxc.org/) (only that one supports passkeys for now).
2. Start KeePassXC, open or create a database.
3. In the KeePassXC settings, enable the browser support, also [install the Chrome extension](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk).
4. In the browser extension settings, enable Passkey generator:
   ![image](https://github.com/dodobrands/WebAuthn.Net/assets/92793/ba7e9b4f-c36b-4c22-99bf-e1c50c8be5f9)
5. Try to register at https://webauthn.vanbukin.com

**Expected result:** same as with other passkey providers, it should generate a new passkey and authenticate.
**Actual result:** KeePassXC successfully shows its window to generate the passkey, but nothing happens after I generate it. The KeePassXC window just closes.

In the browser console, I see the following error message:
```
Uncaught (in promise) TypeError: newCredential.response?.getAuthenticatorData is not a function
    at completeRegistration (lib.js:129:71)
    at HTMLButtonElement.onRegisterButtonHandler (register.js:100:42)
```

Note that KeePassXC works well on the test site https://webauthn.io/, so I believe it is a problem with WebAuthn.Net.

**Comment by Keroosha** [comment]
```
newCredential.response?.getAuthenticatorData
```

Was invalid undefined/null check at demo lib.js, fixed at #5682d8a and now should work fine
