### ISSUE TITLE
CA2263 Error

### ISSUE THREAD

**Issue by jykim-hrc** [dodobrands/WebAuthn.Net#18]
Hi, 
I try this repo.

my environment
- Win10
- VS2022
- .NET8

clone and disabled "global.json" file 

![image](https://github.com/user-attachments/assets/0faa9642-34e3-48a2-a944-29c4c96c022f)

modify target f/w "net6.0;net8.0" -> "net8.0"

![image](https://github.com/user-attachments/assets/b6d28734-b2f2-4d8b-b2f2-ba13abdf197c)

build, many CA2263 error.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2263

![image](https://github.com/user-attachments/assets/58c7ce42-8ea6-4089-b81a-a1774d95372c)

this test situation modify code.

![image](https://github.com/user-attachments/assets/b228023c-07c2-491f-a9ff-c1694153f8ba)

build done.

**Comment by vanbukin** [comment]
Hi! To work correctly with the repository at the moment, you need to install 2 SDK versions locally:
- 6.0.425 or higher
- 8.0.402 or higher

You can view the installed SDKs using the `dotnet --list-sdks` command in your terminal.

You can download the most current versions of the NET SDK from the links:
https://dotnet.microsoft.com/en-us/download/dotnet/6.0
https://dotnet.microsoft.com/en-us/download/dotnet/8.0

You can also run the `dotnet build --configuration Debug` command in the root directory of the project to build the project from the CLI.

**Comment by vanbukin** [comment]
According to the example code, the error doesn't reproduced.

My environment:
- Windows 11 Pro for Workstations 24H2 (26100.2314)
- .NET SDK 6.0.428
- .NET SDK 8.0.404
- Microsoft Visual Studio Enterprise 2022 (17.12.3)
- JetBrains Rider 2024.3

**Comment by jykim-hrc** [comment]
First sorry. 
i am self modify target dotnet version.
vanbukin guide is right! 
i am wrong 😭

create vm.
install dotnet 6 and 8
- 6.0.428 [C:\Program Files\dotnet\sdk]
- 8.0.404 [C:\Program Files\dotnet\sdk]
clone WebAuthn.Net
dotnet build

clean build!


/////////////////////////////////////////////////////
just first content explain 
/////////////////////////////////////////////////////
First content CA2263 error situation is

My main pc
VS2022 Pro(v17.12.3), 
VS2022 install only dotnet 6,8,9 (** installer under install and update only / don't dotnet site download installer exe)
(command line run command)

C:\>dotnet --list-sdks
9.0.101 [C:\Program Files\dotnet\sdk]

clone WebAuthn.Net
disable WebAuthn.Net/globalX.json file
dotnet build

build fail 46 errro and all CA2263
/////////////////////////////////////////////////////

sorry.
and thank you!
